name: Validate AsyncAPI Examples

on:
  push:
    branches:
      - master
      - script-ci-spec-validation

jobs:
  validate_examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generator, Validator, Converter and others - all in one for your AsyncAPI docs
        uses: asyncapi/github-action-for-cli@v3.1.1
            
        with:
          args: "validate ./examples/*.(yml,yaml}"